name: test

on:
  push:
  schedule:
    - cron: '12 3 * * 4'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: update
      run: brew update

    - name: tap
      run: brew tap tbvdm/tap

    - name: uninstall
      run: brew uninstall --force $(brew list)

    - name: test
      run: |
        for f in $(brew --repo tbvdm/tap)/Formula/*.rb; do
          f=$(basename $f .rb)
          brew install --HEAD --verbose $f
          brew test --HEAD --verbose $f
          brew uninstall --force $(brew list)
        done
