name: test

on:
  push:
  schedule:
    - cron: '12 3 * * 4'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: update
      run: brew update

    - name: tap
      run: brew tap tbvdm/tap

    - name: work around soundflower uninstall failure
      if: startsWith(matrix.os, 'macos')
      run: sudo /sbin/kextunload -b com.Cycling74.driver.Soundflower || true

    - name: install
      run: |
        for f in $(brew --repo tbvdm/tap)/Formula/*.rb; do
          f=$(basename $f .rb)
          brew uninstall --force $(brew list)
          brew install --HEAD --verbose $f
        done
