name: test

on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/runner-images/issues/6283
      - name: path
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          d=/home/linuxbrew/.linuxbrew
          echo $d/bin:$d/sbin >> $GITHUB_PATH

      - name: update
        run: brew update

      - name: tap
        run: brew tap tbvdm/tap

      - name: uninstall-casks
        if: startsWith(matrix.os, 'macos')
        run: |
          c=$(brew list --cask)
          [[ -n $c ]] && brew uninstall --force --cask $c

      - name: uninstall-formulae
        run: |
          f=$(brew list --formula)
          if [[ -n $f ]]; then
            brew uninstall --force --formula $f
            # Remove dangling symlinks from the formulae that have just been
            # uninstalled. This prevents problems when some of them are
            # reinstalled later.
            brew cleanup --prune-prefix
          fi

      - name: test
        run: |
          for f in $(brew --repo tbvdm/tap)/Formula/*.rb; do
            f=$(basename $f .rb)
            brew install --HEAD --verbose $f
            brew test --HEAD --verbose $f
            brew uninstall --force $(brew list)
          done
